Luni/Luni/urls.py
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

def error_handler(request, exception=None, status_code=None):

    """
    Tratador de erros genérico para o Django.

    Esta view recebe um request, um exception e um status_code como parâmetros.
    Se o status_code n o for informado, ele padroniza-se como 500.
    A view retorna um HttpResponse com o status code informado e um template
    chamado 'error.html' com dois par metros: status_code e exception.
    O template 'error.html' é responsável por exibir uma página de erro amigável
    ao usuário.

    :param request: O request atual.
    :type request: django.http.HttpRequest
    :param exception: O exception que ocorreu.
    :type exception: Exception
    :param status_code: O status code que será retornado.
    :type status_code: int
    """
    if status_code is None:
        status_code = 500
    context = {
        'status_code': status_code,
        'exception': exception,
    }
    return render(request, 'error.html', context, status=status_code)


handler400 = error_handler
handler403 = error_handler
handler404 = error_handler
handler500 = error_handler


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("principal.urls"), name="index"),
    path("user/", include("usuario.urls"), name='usuario'),
    path("produto/", include("produto.urls"), name='produto'),
    path("estampa/", include("estampa.urls"), name='estampa'),
    path("carrinho/", include("carrinho.urls"), name='carrinho'),
    path("pedido/", include("pedido.urls"), name='pedido'),
    path("accounts/", include("django.contrib.auth.urls")),
    
        # urls para cria o token
    
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Luni/usuario/urls.py
from django.urls import path
from . import views
from .views import TokenObtainPairView
from .views import (
    CreateUsuarioAPIView,
    EditUsuarioAPIView,
    RemoveUsuarioAPIView,
    PerfilUsuarioAPIView,
    ListarUsuariosAPIView,
    MudarTipoUsuarioAPIView,
)


urlpatterns = [
    path('listar_usuarios/', views.listar_usuarios, name='listar_usuarios'), # lista de usuários
    path('<int:id>/mudar_tipo/', views.mudar_tipo, name='mudar_tipo'), # muda o tipo de usuário
    path('perfil/<int:id>/', views.perfil, name='perfil_usuario'), # perfil do usuário
    path('perfil/', views.perfil, name='perfil_usuario'), # perfil do usuário
    path('create/', views.create_usuario, name='create_usuario'), # cria um novo usuário
    path('update/<int:id>/', views.edit_usuario, name='edit_usuario'), # edita um usuário
    path('delete/<int:id>/', views.remove_usuario, name='delete_usuario'), # remove um usuário
    path('receber_suporte_corporativo/', views.receber_suporte_corporativo, name='receber_suporte_corporativo'), # TODO: recebe suporte


    # Novas URLs para a API
    path('usuarios/create/', CreateUsuarioAPIView.as_view(), name='create-usuario'),
    path('usuarios/edit/<int:id>/', EditUsuarioAPIView.as_view(), name='edit-usuario'),
    path('usuarios/delete/<int:id>/', RemoveUsuarioAPIView.as_view(), name='remove-usuario'),
    path('usuarios/perfil/', PerfilUsuarioAPIView.as_view(), name='perfil-usuario'),
    path('usuarios/perfil/<int:id>/', PerfilUsuarioAPIView.as_view(), name='perfil-usuario-id'),
    path('usuarios/', ListarUsuariosAPIView.as_view(), name='listar-usuarios'),
    path('usuarios/mudar-tipo/<int:id>/', MudarTipoUsuarioAPIView.as_view(), name='mudar-tipo-usuario'),
    

]

Luni/usuario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum
from django.utils.functional import cached_property

class Usuario(AbstractUser):
    TIPOS_CLIENTE_DICT = {
        'CLIENTE': 'Cliente', 
        'CORPORATIVO': 'Corporativo', 
        'ADMINISTRADOR': 'Administrador',
    }
    
    TIPOS_CLIENTE = [
        ('CLIENTE', 'Cliente'),
        ('CORPORATIVO', 'Corporativo'),
        ('ADMINISTRADOR', 'Administrador'),
    ]
    
    qnt_itens = None
    
    imagem = models.ImageField(upload_to='usuarios/', blank=True, null=True)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    endereco = models.CharField(max_length=255, blank=True, null=True)
    tipo_cliente = models.CharField(max_length=20, choices=TIPOS_CLIENTE, default='CLIENTE')
    cpf = models.CharField(max_length=11, unique=True, blank=True, null=True)
    
    
    def __str__(self):
        return f"{self.id} - {self.username}"
    
    
    def is_admin(self):
        return self.groups.filter(name="Administrador").exists()
    
    def get_size_items(self):
        carrinho = self.carrinho.first()
        if carrinho:
            return carrinho.itens.aggregate(total_items=Sum('quantidade'))['total_items'] or 0
        return 0

Luni/usuario/forms.py
from django import forms
from django.contrib.auth.forms import SetPasswordMixin
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['imagem', 'username', 'email', 'telefone', 'endereco', 'cpf']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome de usuário'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Digite o e-mail'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o telefone'}),
            'endereco': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o endereço'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o CPF'}),
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    
class UsuarioFormSingup(forms.ModelForm):
    password1, password2 = SetPasswordMixin.create_password_fields()
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'telefone', 'endereco', 'cpf',]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome de usuário'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Digite o e-mail'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o telefone'}),
            'endereco': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o endereço'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o CPF'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Digite a senha'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Digite a senha'}),
        }

        

Luni/usuario/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth import login

from principal.decorators import group_required
from .models import *
from .forms import *

#importes necessarios para o serializers

from rest_framework.views import APIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly

from .serializers import (
    UsuarioSerializer,
    UsuarioCreateSerializer,
    UsuarioUpdateSerializer,
    MudarTipoUsuarioSerializer
)

#import para o token
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

def create_usuario(request):
    """
    Cria um novo usuário.

    Se o request for POST, salva o formulário e faz o login com o novo usuário.
    Se o request for GET, renderiza o formulário de cadastro com um novo usuário.

    :param request: Requisição do HTTP
    :return: Uma página de redirecionamento para a página inicial ou a página de cadastro
    """
    if request.method == "POST":
        form = UsuarioFormSingup(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.set_password(request.POST.get('password1'))
            user.save()
            
            login(request, user)
            grupo, created = Group.objects.get_or_create(name='Clientes')
            
            user.groups.add(grupo)
            return redirect('home')
        else:
            return render(request, "registration/cadastro.html", {"form" : form, 'titulo' : 'Criar Usuário'})
    else:
        form = UsuarioFormSingup()
        return render(request, "registration/cadastro.html", {"form" : form, 'titulo' : 'Criar Usuário'})
    

@login_required
def edit_usuario(request, id):
    """
    Edita um usuário pelo id.

    Se o request for POST, salva o formulário e faz o login com o usuário editado.
    Se o request for GET, renderiza o formulário de edição com o usuário
    correspondente ao id.

    :param request: Requisição do HTTP
    :param id: Id do usuário a ser editado
    :return: Uma página de redirecionamento para a página de perfil do usuário
    """
    if not request.user.is_superuser and id != request.user.id:
        return redirect('perfil_usuario')
        
    usuario = Usuario.objects.filter(pk = id).first()

    if request.method == "POST":
        form = UsuarioForm(request.POST, request.FILES, instance=usuario)

        if form.is_valid():
            user = form.save()
            
            if request.user.id == usuario.id:
                login(request, user)
            
            return redirect('perfil_usuario', id=id)
    else:
        form = UsuarioForm(instance=usuario)
    
    context = {'form' : form, 'titulo' : 'Editar Usuário'}
    
    if usuario.imagem and hasattr(usuario.imagem, 'url'):
        context['current_image_url'] = usuario.imagem.url
    
    return render(request, 'form.html', context)


@login_required
@group_required('Administradores')
def remove_usuario(request, id):
    """
    Remove um usuário pelo id.

    Requer permissão de Administrador.

    :param request: Requisição do HTTP
    :param id: Id do usuário a ser deletado
    :return: Uma página de redirecionamento para a página de listagem de usuários
    """
    usuario = Usuario.objects.filter(pk = id).first()
    
    if usuario: usuario.delete()

    return redirect('listar_usuarios')


@login_required
def perfil(request, id=None):
    """
    Página de perfil do usuário.

    Se o usuário não for administrador e tentar acessar o perfil de outro usuário,
    redireciona para o perfil do usuário logado.

    :param request: Requisição do HTTP
    :param id: Opcional, id do usuário a ser visualizado. Se não for passado,
               redireciona para o perfil do usuário logado.
    :return: Uma página renderizada com o perfil do usuário
    """
    if not request.user.is_superuser and id is not None and id != request.user.id:
        return redirect('perfil_usuario')
    
    user = None
    if id:
        user = get_object_or_404(Usuario, pk=id)
    else:
        user = request.user
    
    form = UsuarioForm(instance=user)
    
    return render(request, 'usuario/perfil.html', {'form': form, 'user': user, 'titulo' : 'Perfil do Usuário'})


@login_required
@group_required('Administradores')
def mudar_tipo(request, id):
    """
    Muda o tipo do usuário pelo id.

    Requer permissão de Administrador.

    :param request: Requisição do HTTP
    :param id: Id do usuário a ter o tipo mudado
    :return: Uma página de redirecionamento para a página de perfil do usuário
    """
    if request.method == "POST":
        tipo = request.POST.get('tipo', "Cliente")
        user = get_object_or_404(Usuario, pk=id)

        if tipo == "CLIENTE":
            user.groups.clear()
            user.is_superuser = False
            user.tipo_cliente = tipo
            grupo, created = Group.objects.get_or_create(name='Clientes')
            user.groups.add(grupo)

        elif tipo == "ADMINISTRADOR":
            user.groups.clear()
            user.tipo_cliente = tipo
            user.is_superuser = True
            grupo, created = Group.objects.get_or_create(name='Administradores')
            user.groups.add(grupo)
            
        elif tipo == "CORPORATIVO":
            user.groups.clear()
            user.is_superuser = False
            user.tipo_cliente = tipo
            grupo, created = Group.objects.get_or_create(name='Corporativos')
            user.groups.add(grupo)
            
        user.save()
        messages.success(request, f"Tipo de usuário alterado com sucesso para {Usuario.TIPOS_CLIENTE_DICT[tipo]}.")
    
    return redirect('perfil_usuario', id=id)


@login_required
@group_required('Administradores')
def listar_usuarios(request):
    """
    Mostra uma lista de todos os usuários.

    Requer permissão de Administrador.

    :param request: Requisição do HTTP
    :return: Uma página HTML com a lista de usuários.
    """
    usuarios = Usuario.objects.all()
    return render(request, 'usuario/listar_usuarios.html', {'usuarios': usuarios})


def receber_suporte_corporativo(request):
    """
    Mostra uma página para os usuários corporativos.

    Se o usuário for administrador, renderiza a página de suporte corporativo.
    Senão, exibe uma mensagem de erro e redireciona para a página inicial.

    :param request: Requisição do HTTP
    :return: Uma página HTML de suporte corporativo ou uma página de erro.
    """
    if request.user.groups.filter(name='Administradores').exists():
        return render(request, 'support/receber_suporte_corporativo.html')
    
    messages.error(request, 'Você não tem permissão para acessar esta página. Para ter uma conta corporativa entre em contato com luni.support@gmail.com')
    
    return redirect('home')


#criação do views APIs para serializers

class CreateUsuarioAPIView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = UsuarioCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class EditUsuarioAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def patch(self, request, id):
        usuario = get_object_or_404(Usuario, pk=id)

        if not request.user.is_superuser and int(id) != request.user.id:
            return Response(
                {"detail": "Você não tem permissão para editar este usuário."},
                status=status.HTTP_403_FORBIDDEN
            )

        serializer = UsuarioUpdateSerializer(usuario, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RemoveUsuarioAPIView(APIView):
    permission_classes = [IsAuthenticated]  # Apenas usuários autenticados podem deletar contas

    def delete(self, request, id):
        usuario = get_object_or_404(Usuario, pk=id)

        if not request.user.is_superuser and usuario.id != request.user.id:
            return Response(
                {"detail": "Você não tem permissão para excluir este usuário."},
                status=status.HTTP_403_FORBIDDEN
            )

        usuario.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class PerfilUsuarioAPIView(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]  # Usuários autenticados podem ver perfis, outros podem ver públicos

    def get(self, request, id=None):
        if id:
            usuario = get_object_or_404(Usuario, pk=id)
        elif request.user.is_authenticated:
            usuario = request.user
        else:
            return Response({"detail": "Usuário não encontrado."}, status=status.HTTP_404_NOT_FOUND)

        serializer = UsuarioSerializer(usuario)
        return Response(serializer.data)


class ListarUsuariosAPIView(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]  # Apenas usuários autenticados podem listar

    def get(self, request):
        usuarios = Usuario.objects.all()
        serializer = UsuarioSerializer(usuarios, many=True)
        return Response(serializer.data)


class MudarTipoUsuarioAPIView(APIView):
    permission_classes = [IsAuthenticated]  # Apenas usuários autenticados podem mudar o tipo de usuário

    def post(self, request, id):
        usuario = get_object_or_404(Usuario, pk=id)

        if not request.user.is_superuser:
            return Response(

Luni/templates/usuario/listar_usuarios.html
{% extends "principal/settings.html" %} {% block title %}Listar Usuários
{% endblock title %} {% block settings_content %}
    <div class="form-row">
        <a href="{% url "create_usuario" %}" class="btn-primary">Nova usuário</a>
    </div>
    <br>

    <h2>Lista de Usuários</h2>
    <br>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Tipo</th>
                <th colspan="2">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.tipo_cliente }}</td>
                <td>
                    <form
                        method="POST"
                        action="{% url 'delete_usuario' usuario.id %}"
                        style="display: inline"
                    >
                        {% csrf_token %}
                        <div
                            class="d-flex justify-content-between"
                            style="gap: 1rem"
                        >
                            <button
                                type="button"
                                onclick="window.location='{% url 'perfil_usuario' usuario.id %}'"
                                class="btn-primary"
                            >
                                Editar
                            </button>
                            <button
                                type="submit"
                                style="background-color: #d45959"
                                class="btn-primary"
                                onclick="return confirm('Tem certeza que deseja deletar este usuário?');"
                            >
                                Deletar
                            </button>
                        </div>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Não há nenhum usuário cadastrado</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock settings_content %}

Luni/templates/usuario/perfil.html
{% extends "base/_base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load custom_tags %}

{% block title %}Perfil{% endblock title %}

{% block content %}
<div class="container-product">
    <div class="form-container">
        <div class="d-flex justify-content-between">
            <h2>Perfil do Usuário</h2> 
            <form action="{% url "logout" %}" method="post" class="form-row icon-header-item">
                {% csrf_token %}
                <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="{{ user|get_size_items }}">
                    <a href="{% url "carrinho" id=user.id %}" class="hov-cl1 cl2" title="Meu carrinho">
                        <i class="zmdi zmdi-shopping-cart"></i>
                    </a>
                </div>
                <div class="icon-header-item cl2 hov-cl1 trans-04 js-show-cart">
                    <a href="{% url "listar_pedidos" id=user.id %}" class="hov-cl1 cl2" title="Meus pedidos">
                        <i class="zmdi zmdi-view-list"></i>
                    </a>
                </div>
                {% if request.user.id == user.id %}
                    <button type="submit" class="hov-cl1 cl2" title="Sair">
                        <i class="zmdi zmdi-power"></i>
                    </button>
                {% endif %}
            </form>
        </div>
        <hr>
        {% if request.user.is_superuser %}
            <div class="form-group">
                <label class="stext-102 cl3">Tipo de usuário: </label>
                <input type="text" disabled value="{{ user.tipo_cliente }}" class="form-control">
            </div>
        {% endif %}
        
        <form method="POST" action="{% url "edit_usuario" id=user.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label class="stext-102 cl3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <p class="custom-class">
                    {% if field.field.widget.input_type == "file" %}
                        <div class="image-container">
                            <hr>
                            {% if user.imagem %}
                                <div class="img-placeholder d-flex justify-content-center">
                                    <img class="perfil image-default" id="image-preview" onerror="this.src='{% static "images/user-profile.jpg" %}'; this.style.display='block';" src="{{ user.imagem.url }}" alt="Imagem atual" />
                                </div>
                                <label class="checkbox-label">
                                    <input type="checkbox" name="imagem-clear" id="imagem-clear_id">
                                    Limpar
                                </label>
                            {% else %}
                                <div class="d-flex justify-content-center">
                                    <img class="perfil image-default" id="image-preview" src="{% static "images/user-profile.jpg" %}" alt="Imagem preview" />
                                </div>    
                            {% endif %}
                            <hr>
                            <input type="file" name="imagem" class="form-control" accept="image/*" id="id_imagem">
                            <p class="file-status">Nenhum arquivo escolhido</p>
                        </div>
                    {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}
                </p>
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {% endfor %}
            
            <div class="form-row">
                <input type="submit" id="confirm-btn" onclick="confirmarAlteracao()" class="btn-primary" value="Atualizar Perfil"/>
                <a href="{% url "password_change" %}" class="btn-primary"/>Mudar a senha</a>
            </div>
        </form>

        {% if user is not null and request.user.id != user.id %}
            {% if request.user.is_superuser %}
            <form id="mudar-tipo-form" action="{% url 'mudar_tipo' id=user.id %}" method="post">
                <hr>
                <br>
                <h3>Admin: Mudar tipo de usuário </h3>
                <br>
                <div class="form-row">
                    {% csrf_token %}
                    <button type="submit" name="tipo" class="btn-primary ml-2" value="CLIENTE" onclick="confirmarAlteracao('CLIENTE')">Tornar em cliente comum</button>
                    <button type="submit" name="tipo" class="btn-primary ml-2" value="ADMINISTRADOR" onclick="confirmarAlteracao('ADMINISTRADOR')">Tornar em um administrador</button>
                    <button type="submit" name="tipo" class="btn-primary ml-2" value="CORPORATIVO" onclick="confirmarAlteracao('CORPORATIVO')">Tornar usuário em Corporativo</button>
                </div>
            </form>
            {% endif %}
        {% endif %}
    </div>
</div>

<style>
    .img-placeholder {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .image-container {
        text-align: center;
    }
</style>
{% endblock content %}

{% block extra_js %}
<script>
    function confirmarAlteracao() {
        return confirm('Tem certeza que deseja atualizar este perfil?');
    }

    document.addEventListener('DOMContentLoaded', function() {
        const fileInput = document.querySelector('input[type="file"]');
        const preview = document.getElementById('image-preview');

        if (fileInput) {
            fileInput.addEventListener('change', function(event) {
                const file = event.target.files[0];
                
                if (file) {
                    const reader = new FileReader();
                    
                    reader.onload = function(e) {
                        preview.src = e.target.result;
                        preview.style.display = 'block';
                    };
                    
                    reader.readAsDataURL(file);
                }
            });
        }
    });
</script>
{% endblock extra_js %}